export { default as Footer } from "./Footer"
export { default as Navbar } from "./Navbar"
export { default as Contact } from "./Contact"
export { default as Projects } from "./Projects"
export { default as Qualifications } from "./Qualifications"
export { default as Services } from "./Services"
export { default as HeroSection } from "./HeroSection"